pipeline {
    agent any
    
    tools {
        maven "maven3.9"
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
            post {
                success{
                    echo "Archiving the Artifacts"
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
        stage ('Deploy to tomcat server'){
            steps{
                deploy adapters: [tomcat9(credentialsId: 'd2d9577c-e7cb-439d-b737-67431042b3e6', path: '', url: 'http://localhost:7080/')], contextPath: null, war: '**/*.war'
            }
        }
    }
}